### ISSUE TITLE
error in data binding

### ISSUE THREAD

**Issue by jozifen** [lfmachadodasilva/MyExpenses#147]
hey there ,
I'm working on angular project , so I wanna update a user by transformings his data to a form BUT I keep getting this error all the time:
```
ERROR TypeError: Cannot read property 'cin' of undefined
    at Object.eval [as updateDirective
```
cin is the id of the user 
can anybody help me???

**Comment by lfmachadodasilva** [comment]
Hi @jozifen 
Unfortunately the project has not evolved to use Angular yet. For now, the MVC is still being used.
Also, I have no expertise in Angular :)
